spring:
  application:
    name: config
  zipkin:
    base-url: http://192.168.244.132:9411
eureka:
  client:
    service-url:
      defaultZone: http://192.168.244.132:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always