version: '3'
services:
  zuul:
    restart: always
    image: 192.168.244.130:5000/zuul
    container_name: zuul
    ports:
      - 8769:8769
    networks:
      - zuul_network

networks:
  zuul_network: