stages:
  - build
  - push
  - run

build:
  stage: build
  script:
    - /usr/local/maven/apache-maven-3.6.0/bin/mvn clean package
    - cp target/config-0.0.1-SNAPSHOT.jar docker
    - cd docker
    - docker build -t 192.168.244.130:5000/config .

push:
  stage: push
  script:
    - docker push 192.168.244.130:5000/config

run:
  stage: run
  script:
    - cd docker
    - docker-compose down
    - docker-compose up -d
    - docker rmi $(docker images -q -f dangling=true)
