spring:
  application:
    name: admin
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: vhans
#    password: luowei4628@()
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  zipkin:
    base-url: http://192.168.244.132:9411
  security:
    user:
      name: "vhans"
      password: "luowei4628@()"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://192.168.244.132:8761/eureka/,http://192.168.244.132:8861/eureka/,http://192.168.244.132:8961/eureka/
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}