spring:
  application:
    name: service-redis
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.244.129:26379, 192.168.244.129:26380, 192.168.244.129:26381

server:
  port: 8302