spring:
  application:
    name: service-admin
  datasource:
    druid:
      url: jdbc:mysql://192.168.244.129:3306/service-admin?useUnicaode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: luowei4628@()
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.244.129:26379, 192.168.244.129:26380, 192.168.244.129:26381

server:
  port: 8301

mybatis:
  type-aliases-package: com.provide.commondomain.domain
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    cache-enabled: true